# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 50
    commit-message:
      prefix: "Node/Bun - "
    directory: "/site"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "Submodule - "
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Github Actions - "
    directory: ./.github/actions/DockerCache
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Github Actions - "
    directory: ./.github/actions/VersionString
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Github Actions - "
    directory: ./.github/actions/PopulateBuildSummary
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Github Actions - "
    directory: ./.github/workflows/
    schedule:
      interval: "daily"